version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
      - "81:80"
    volumes:
      - ../battleship:/var/www
      - ./1-site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - battleship
    expose:
      - "8081"

#  mysql:
#    image: mysql:5.6
#    container_name: "mysql-container"
#    volumes:
#      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=123

  php-fpm-72:
    build: ./php/
    container_name: "php-container"
    volumes:
      - ../battleship:/var/www
    ports:
      - "8001:9000"
      - "9001:9000"
    expose:
      - "9001"
    networks:
      - battleship
#    links:
#      - mysql
#    environment:
#      - DB_PASSWORD=123
#      - DB_HOST=db
#    depends_on:
#      - mysql

#  mailhog:
#    image: mailhog/mailhog:v1.0.0
#    ports:
#      - "1025:1025"
#      - "8025:8025"

networks:
  battleship: {}
